version: "2"
services:
  database:
    image: postgres:11
    container_name: db
    hostname: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: worker
      POSTGRES_PASSWORD: worker
      POSTGRES_HOST_AUTH_METHOD: trust
    networks:
      - my_network
    volumes:
      - db_volume:/var/lib/postgresql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - "5000:5000"
    depends_on:
      - database
    links:
      - database:database
    environment:
      DB_URL: postgresql://worker:worker@db/app
      POSTGRESQL_URL: postgresql://worker:worker@db:5432/app
      POSTGRES_HOST: db
      PERSISTENCE_TYPE: postgres
      WAIT_HOSTS: db:5432
    hostname: app
    container_name: app
    networks:
      - my_network

  webserver:
    image: nginx:1.18.0
    container_name: web
    ports:
     - "8080:80"
   # volumes:
     # - ./conf.d:/etc/nginx/conf.d
    networks:
      - my_network
    depends_on:
      - database

networks:
  my_network:
    driver: bridge
volumes:
  db_volume: